[project]
name = "torchdevice"
version = "0.1.3"
description = "Setup CUDA_VISIBLE_DEVICES"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "filelock>=3.19.1",
    "torch>=2.8.0",
]
